name: Bandit Security Testing
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install nbconvert==6.3.0
          python -m pip install bandit==1.7.1
      - name: Convert notebooks to Python
        run: |
          find ./src \
            -type f -name "*.ipynb" \
            -exec jupyter-nbconvert \
            --to python \
            --TemplateExporter.exclude_markdown=true {} \;
      - name: Run bandit
        run: |
          bandit --verbose --recursive ./src
